server:
  undertow:
    accesslog:
      # 日志存放目录
      dir: ./logs
# logback
logging:
  file:
    path: ./logs
# 全局自定义的一些配置
global:
  # 异步线程池配置(监听器 or 定时任务使用)
  async:
    thread-pool:
      enable: true
      executors:
        - threadPoolName: testListener
          keepAliveSeconds: 5
  # Jwt安全相关配置
  jwt:
    security:
      enable: true
      secret: U0JBUDud82frFt8YHk9uZz0yNjQ1NA==
      issuer: Elliot
      param-key: SpringBootRefactorDDD
  # Akka配置
  akka:
    enable: true
    refresh-configuration: false