server:
  undertow:
    accesslog:
      # 日志存放目录
      dir: ./logs
# logback
logging:
  file:
    path: ./logs
# 异步线程池配置(监听器 or 定时任务使用)
global:
  async:
    thread-pool:
      enable: true
      executors:
        - threadPoolName: testListener
          keepAliveSeconds: 5